version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper   ## 镜像
    restart: unless-stopped
    hostname: zookeeper
    ports:
      - "2181:2181"                 ## 对外暴露的端口号
    container_name: zookeeper
  kafka:
    image: wurstmeister/kafka       ## 镜像
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.99      ## 修改:宿主机IP
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181       ## kafka基于zookeeper
    depends_on:
      - zookeeper
    container_name: kafka
  kafka-manager:  
    image: sheepkiller/kafka-manager                ## 镜像：开源的web管理kafka集群的界面
    environment:
        ZK_HOSTS: 192.168.0.99                      ## 修改:宿主机IP
    ports:  
      - "19000:9000"                                 ## 暴露端口
    depends_on: 
      - kafka
    container_name: kafka-manager

